### ISSUE TITLE
AssertionError: missing path thrown when using require opt

### ISSUE THREAD

**Issue by charlesdeuter** [sindresorhus/gulp-mocha#140] opened 2016-08-25 02:31 UTC
When running my gulp test task I get a missing path error. I've trouble shot it down to the the `require : [test/tests.js]` line in my gulp task.

Here is the error:

```
[18:57:39] 'test' errored after 98 ms
[18:57:39] AssertionError: missing path
    at Module.require (module.js:481:3)
    at require (internal/module.js:20:19)
    at module.exports (/Users/charlesdeuter/repos/waterfront-client/node_modules/req-from/index.js:5:9)
    at module.exports (/Users/charlesdeuter/repos/waterfront-client/node_modules/req-cwd/index.js:5:9)
    at /Users/charlesdeuter/repos/waterfront-client/node_modules/gulp-mocha/index.js:29:4
    at Array.forEach (native)
    at module.exports (/Users/charlesdeuter/repos/waterfront-client/node_modules/gulp-mocha/index.js:28:16)
    at Gulp.<anonymous> (test.js:21:9)
    at module.exports (/Users/charlesdeuter/repos/waterfront-client/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/charlesdeuter/repos/waterfront-client/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/charlesdeuter/repos/waterfront-client/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /Users/charlesdeuter/repos/waterfront-client/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/Users/charlesdeuter/repos/waterfront-client/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/charlesdeuter/repos/waterfront-client/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/charlesdeuter/repos/waterfront-client/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/charlesdeuter/repos/waterfront-client/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
```

Here is my gulp task:

``` javascript
gulp.task('test', function() {
  return gulp.src(TEST_FILES, {read: false})
    .pipe(mocha({
      require: ['test/tests.js'] // Prepare environement for testing
    }));
});
```

Here is the setup file:

``` javascript
console.log('test js executed as expected');  
const chai = require('chai');
// Load Chai assertions
global.expect = chai.expect;
global.assert = chai.assert;
global.should = chai.should();
// Load Sinon
global.sinon = require('sinon');
// Initialize Chai plugins
chai.use(require('sinon-chai'));
```

curiously enough if I throw a `module.exports = this;` at the bottom of the setup file, it doesn't throw an error (although the code doesn't appear to execute).

Any thoughts?

**Comment by zauzaj** [comment] 2016-09-27 15:02
Hi @charlesdeuter , I have similar problem . Did you maybe solve this issue ?

**Comment by ohkaiby** [comment] 2016-12-06 19:56
Just ran into this as well. Looking at the stack trace, the problem is at a related required module: https://github.com/sindresorhus/resolve-from/blob/master/index.js.

Basically the `require` option only allows you to include modules that are already in `node_modules/`, and not custom-defined modules that are sitting somewhere in your project folder.

**Comment by sindresorhus** [comment] 2017-02-20 15:21
Should be fixed in the latest release: https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0

**Closed by sindresorhus** 2017-02-20 15:21 UTC
